version: '3.1'

services:
  app-laravel:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - CHOKIDAR_USEPOLLING=true   # Para que Vite detecte cambios dentro de Docker
    depends_on:
      - db
