version: '3.1'

services:
  app-laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - test_mysql-net
    depends_on:
      - db

  node:
      image: node:22-slim
      working_dir: /var/www
      volumes:
        - .:/var/www
      command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
      ports:
        - "5173:5173"
  db:
    container_name: mysql8.3.0
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-laravel-test:/var/lib/mysql
    networks:
      - test_mysql-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  # redis:
  #   image: 'redis:alpine'
  #   ports:
  #     - '${FORWARD_REDIS_PORT:-6379}:6379'
  #   volumes:
  #     - 'sail-redis:/data'
  #   networks:
  #     - test_mysql-net
  #   healthcheck:
  #     test:
  #       - CMD
  #       - redis-cli
  #       - ping
  #     retries: 3
  #     timeout: 5s
  phpmyadmin:
    container_name: phpmyadmin5.2
    image: phpmyadmin:5.2-apache
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - test_mysql-net
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # PMA_USER: user  
      # PMA_PASSWORD: pass

networks:
  test_mysql-net:
    driver: bridge

volumes:
  mysql-laravel-test:   # Definici√≥n del volumen externo
      external: true 